// Deliverable 3: Import / Add `Button` Styled Component

  // How can we make `Button` render to the DOM as a `Link` component?

  import { NavLink, Link } from "react-router-dom";

  import { Button } from "./shared";

  const Header = ({ isDarkMode, onToggleDarkMode }) => {
    const buttonTextContent = isDarkMode ? "Light Mode" : "Dark Mode";
  
    return (
      <header className="navigation">
        <h1 className="branding">
          <Link to="/">
            <span className="logo">{"//"}</span>
            Project Showcase
          </Link>
        </h1>
        <nav>
          {/* as => Pass To Styled Components to Override DOM Rendering */}
          <Button as={NavLink} exact to="/projects">
            All Projects
          </Button>
          <Button as={NavLink} to="/projects/new">
            Add Project
          </Button>
          <Button as={NavLink} to="/about">
            About
          </Button>
          
          {/* class="sc-gKPRtg gXWGCs" => Generated By styled-components */}
            {/* Reduces The Likelihood Of Conflicting CSS Class Styles */}
          <Button onClick={onToggleDarkMode}>{buttonTextContent}</Button>
        </nav>
      </header>
    );
  };
  
  export default Header;
  